### ISSUE TITLE
Includes files not included

### ISSUE THREAD

**Issue by dougmasten** [nowhereman999/CoCo3_MemTest2023#2]
Could you add "./includes/CoCo3_Start.asm" and "./includes/Macros.asm" files to the repo so it can be assembled?
Thanks!

**Comment by nowhereman999** [comment]
Hi Doug, I uploaded the includes.zip file with v1.01 which has dark blue for the background colour and white for the text.  Unzip the incudes into each own folder with the main source file and it should now assemble.  I use my own loader to use the program, as it run in very low RAM and will kill itself if loaded using regular disk basic.
I'd like to get your email address for the future.  Please email me at nowhereman999 at yahoo dot com
Cheers,
Glen
